sudo: required
language: erlang
otp_release:
  - 19.2
  - 18.3
services:
  - riak
before_install:
  - ./ci before_install "${PWD:?}"/rebar3
install:
  - ./ci install "${PWD:?}"/rebar3
before_script:
  - ./ci before_script
script:
  - ./ci script "${PWD:?}"/rebar3 http://127.0.0.1:8098 maps sumo_test_index
cache:
  directories:
    - .plt

